In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [10]:
dataset = pd.read_csv('/content/drive/MyDrive/Arquivos_Doutorado/Trabalhos_Disciplinas/Machine Learning - Gustavo/dataset2.csv', sep=';')

dataset = pd.get_dummies(dataset,drop_first=True)
X = dataset.iloc[:,0:18]
#X2 = dataset.iloc[:, 8:]
X

Sexo  Idade  turno  ...  usoucocaína  preservativo  exercfísico
0       1      1      0  ...            0             0            0
1       0      1      0  ...            0             0            0
2       0      1      0  ...            0             1            1
3       1      1      0  ...            0             0            1
4       1      1      0  ...            0             0            1
..    ...    ...    ...  ...          ...           ...          ...
897     0      1      1  ...            0             0            0
898     0      0      1  ...            0             0            1
899     0      1      1  ...            0             0            1
900     0      1      1  ...            0             1            1
901     0      1      1  ...            0             0            1

[902 rows x 18 columns]

In [11]:

#X = pd.concat([X1,X2],axis=1)
#X
y = dataset.iloc[:,18:19]
y

tentousuicídio
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
897               0
898               0
899               0
900               0
901               0

[902 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size = 0.25, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Regressao Logistica
import numpy as np
from sklearn.linear_model import LogisticRegression
logclassifier = LogisticRegression(random_state = 0)
logclassifier.fit(X_train, np.ravel(y_train,order='C'))

y_pred_log = logclassifier.predict(X_test)
y_pred_log

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [14]:
# Matriz de Confusão
from sklearn.metrics import confusion_matrix
cmlog = confusion_matrix(y_test, y_pred_log)
cmlog

array([[218,   1],
       [  6,   1]])

In [15]:
accuracy = (cmlog[0,0]+cmlog[1,1])/cmlog.sum()
accuracy

0.9690265486725663

In [16]:
#SVM
from sklearn.svm import SVC
svmclassifier = SVC(kernel = 'rbf', random_state = 0)
svmclassifier.fit(X_train, np.ravel(y_train, order='C'))

y_pred_svm = svmclassifier.predict(X_test)
y_pred_svm

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [17]:
#Matriz de Confusao
from sklearn.metrics import confusion_matrix
cmsvm = confusion_matrix(y_test, y_pred_svm)
cmsvm

array([[219,   0],
       [  7,   0]])

In [18]:
accuracy = (cmsvm[0,0]+cmsvm[1,1])/cmsvm.sum()
accuracy

0.9690265486725663

In [21]:
#REDE NEURAL

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Arquivos_Doutorado/Trabalhos_Disciplinas/Machine Learning - Gustavo/dataset2.csv', sep=';')
dataset = pd.get_dummies(dataset,drop_first=True)
X = dataset.iloc[:,0:18]
y = dataset.iloc[:,18:19]
y

tentousuicídio
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
897               0
898               0
899               0
900               0
901               0

[902 rows x 1 columns]

In [22]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling, é necessário para manter o as variáveis no mesmo range 
#e não fazer com que alguma variável sobreponha as outras
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Primeira Camada: Entrada
classifier.add(Dense(units = 11, kernel_initializer = 'uniform', activation = 'relu'))

# Segunda Camada: hidden layer
classifier.add(Dense(units = 11, kernel_initializer = 'uniform', activation = 'relu'))

# Terceira Camada: output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


# Compiling the ANN
# O parâmetro "optimizer" refere-se ao algoritmo para otimizar os pesos. O algoritmo Adam 
# é um algoritimo Gradient Discent Estocático
# loss é o erro que se quer minimizar, logaric miss loss é usado quando a camada de saída é a sigmoid
# metrics é usado para mostrar a evolução da métrica escolhida durante o treinamento
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


# Fitting the ANN to the Training set

# batch_size é o número de observações que será usada para altualizar os pesos
# O batch_size é um hiperparâmetro de gradiente descendente que controla o número de amostras de treinamento 
# a serem trabalhadas antes que os parâmetros internos do modelo sejam atualizados.
# O Epochs é um hiperparâmetro do gradiente descendente que controla o número de passagens completas pelo 
#conjunto de dados de treinamento.

classifier.fit(X_train, y_train, epochs=100,batch_size = 10)

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
# transformar em true or false para usar na confusion matrix
y_pred = (y_pred > 0.5)
len(y_pred)


Epoch 1/100
73/73 [==============================] - 1s 1ms/step - loss: 0.6797 - accuracy: 0.9115
Epoch 2/100
73/73 [==============================] - 0s 1ms/step - loss: 0.5301 - accuracy: 0.9794
Epoch 3/100
73/73 [==============================] - 0s 1ms/step - loss: 0.2202 - accuracy: 0.9698
Epoch 4/100
73/73 [==============================] - 0s 1ms/step - loss: 0.1019 - accuracy: 0.9722
Epoch 5/100
73/73 [==============================] - 0s 2ms/step - loss: 0.0965 - accuracy: 0.9626
Epoch 6/100
73/73 [==============================] - 0s 1ms/step - loss: 0.0593 - accuracy: 0.9783
Epoch 7/100
73/73 [==============================] - 0s 1ms/step - loss: 0.0620 - accuracy: 0.9745
Epoch 8/100
73/73 [==============================] - 0s 1ms/step - loss: 0.0613 - accuracy: 0.9707
Epoch 9/100
73/73 [==============================] - 0s 1ms/step - loss: 0.0619 - accuracy: 0.9689
Epoch 10/100
73/73 [==============================] - 0s 1ms/step - loss: 0.0554 - accuracy: 0.9736
Epoch 11/

181

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[176,   0],
       [  4,   1]])

In [24]:
accuracy = (cm[0,0]+cm[1,1])/cm.sum()
accuracy

0.9779005524861878